config/routes.rb
Automan::Application.routes.draw do
  resources :vehiculos

  devise_for :usuarios

  get "home/index"

  root :to => "home#index"

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :vehiculos, :dependent => :destroy
end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
  belongs_to :usuario
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/vehiculos_controller.rb
class VehiculosController < ApplicationController
  before_filter :authenticate_usuario!

  # GET /vehiculos
  # GET /vehiculos.xml
  def index
#    @vehiculos = Vehiculo.all
    @vehiculos = current_usuario.vehiculos

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @vehiculos }
    end
  end

  # GET /vehiculos/1
  # GET /vehiculos/1.xml
  def show
    @vehiculo = Vehiculo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vehiculo }
    end
  end

  # GET /vehiculos/new
  # GET /vehiculos/new.xml
  def new
    @vehiculo = Vehiculo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vehiculo }
    end
  end

  # GET /vehiculos/1/edit
  def edit
    @vehiculo = Vehiculo.find(params[:id])
  end

  # POST /vehiculos
  # POST /vehiculos.xml
  def create
    @vehiculo = Vehiculo.new(params[:vehiculo])
    @vehiculo.usuario = current_usuario

    respond_to do |format|
      if @vehiculo.save
        format.html { redirect_to(@vehiculo, :notice => 'Vehiculo was successfully created.') }
        format.xml  { render :xml => @vehiculo, :status => :created, :location => @vehiculo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @vehiculo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vehiculos/1
  # PUT /vehiculos/1.xml
  def update
    @vehiculo = Vehiculo.find(params[:id])

    respond_to do |format|
      if @vehiculo.update_attributes(params[:vehiculo])
        format.html { redirect_to(@vehiculo, :notice => 'Vehiculo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vehiculo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vehiculos/1
  # DELETE /vehiculos/1.xml
  def destroy
    @vehiculo = Vehiculo.find(params[:id])
    @vehiculo.destroy

    respond_to do |format|
      format.html { redirect_to(vehiculos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= link_to "Mis Vehículos", vehiculos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auto Mantenimiento</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <%= link_to "Auto Mantenimiento", root_path %>

  <div>
    <p>
    <% if current_usuario %>
      Usuario: <%= current_usuario.email %> | <%= link_to "Logout", destroy_usuario_session_path %>
    <% else %>
      <%= link_to "Registrarse", new_usuario_registration_path %> | <%= link_to "Login", new_usuario_session_path %>
    <% end %>
    </p>
  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/vehiculos/_form.html.erb
<%= form_for(@vehiculo) do |f| %>
  <% if @vehiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehiculo.errors.count, "error") %> prohibited this vehiculo from being saved:</h2>

      <ul>
      <% @vehiculo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marca %><br />
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :modelo %><br />
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :anio %><br />
    <%= f.text_field :anio %>
  </div>
  <div class="field">
    <%= f.label :kms %><br />
    <%= f.text_field :kms %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehiculos/edit.html.erb
<h1>Editing vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehiculo %> |
<%= link_to 'Back', vehiculos_path %>

app/views/vehiculos/index.html.erb
<h1>Listing vehiculos</h1>

<table border="1">
  <tr>
    <th>Marca</th>
    <th>Modelo</th>
    <th>Anio</th>
    <th>Kms</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vehiculos.each do |vehiculo| %>
  <tr>
    <td><%= vehiculo.marca %></td>
    <td><%= vehiculo.modelo %></td>
    <td><%= vehiculo.anio %></td>
    <td><%= vehiculo.kms %></td>
    <td><%= link_to 'Show', vehiculo %></td>
    <td><%= link_to 'Edit', edit_vehiculo_path(vehiculo) %></td>
    <td><%= link_to 'Destroy', vehiculo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vehiculo', new_vehiculo_path %>

app/views/vehiculos/new.html.erb
<h1>New vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Back', vehiculos_path %>

app/views/vehiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Marca:</b>
  <%= @vehiculo.marca %>
</p>

<p>
  <b>Modelo:</b>
  <%= @vehiculo.modelo %>
</p>

<p>
  <b>Anio:</b>
  <%= @vehiculo.anio %>
</p>

<p>
  <b>Kms:</b>
  <%= @vehiculo.kms %>
</p>

<%= link_to 'Edit', edit_vehiculo_path(@vehiculo) %> |
<%= link_to 'Back', vehiculos_path %>